set nocompatible
set hidden
set number
set ruler

set encoding=utf-8

set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set list listchars=tab:\ \ ,trail:·

set hlsearch
set incsearch
set ignorecase
set smartcase

filetype off

set guifont=Inconsolata:h16

set backupdir=~/.vim/backup
set directory=~/.vim/backup

runtime! macros/matchit.vim

set showcmd

" Commands
set pastetoggle=<F10>
cmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

let mapleader = "\<Space>"
nnoremap <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>
nnoremap <Leader>w :w<CR>
nnoremap <Leader>b :b
nnoremap <Leader>bd :bd<CR>
nnoremap <Leader>bn :bn<CR>
nnoremap <Leader>bp :bp<CR>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>v :vs<CR>
nmap <Leader><Leader> V

autocmd BufNewFile,BufRead Vagrantfile set filetype=ruby

" Treate eco files as html for autoclose
au Filetype eco so ~/.vim/bundle/HTML-AutoCloseTag/ftplugin/html_autoclosetag.vim

"vmap <C-c> :<Esc>`>a<CR><Esc>mx`<i<CR><Esc>my'xk$v'y!xclip -selection c<CR>u
"map <Insert> :set paste<CR>i<CR><CR><Esc>k:.!xclip -o<CR>JxkJx:set nopaste<CR>

" Vundle and plugins
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'tpope/vim-unimpaired'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rails'

Plugin 'vim-scripts/matchit.zip'
" Plugin "MarcWeber/vim-addon-mw-utils"
" Plugin "tomtom/tlib_vim"
" Plugin "garbas/vim-snipmate"
Plugin 'scrooloose/syntastic'
Plugin 'pangloss/vim-javascript'
Plugin 'kchmck/vim-coffee-script'
Plugin 'AndrewRadev/vim-eco'
Plugin 'vim-scripts/HTML-AutoCloseTag'
" Plugin 'fatih/vim-go'

" Plugin 'ekalinin/Dockerfile.vim'
" Plugin 'matthewsimo/angular-vim-snippets'

" Plugin 'wting/rust.vim'
Plugin 'raichoo/haskell-vim'
Plugin 'elixir-lang/vim-elixir'
Plugin 'Valloric/YouCompleteMe'
" Optional:
" Plugin 'honza/vim-snippets'
call vundle#end()

syntax enable
filetype plugin indent on

" Don't autoinstall go plugins every startup
let g:go_disable_autoinstall = 1
